### ISSUE TITLE
Wrong precedence

### ISSUE THREAD

**Issue by vigna** [vpxyz/xorshift#2]
https://github.com/vpxyz/xorshift/blob/8d82472a25228b91dd01e9ad6dd96f45b0eac715/xoroshiro128plus/xoroshiro128plus.go#L61

Someone make my notice that the precedence here is wrong. The code is not equivalent to my C code.

For PRNGs, I always suggest some unit testing based on another implementation (like, 10 values must be the same given a seed). It's very easy to slip.

**Comment by vpxyz** [comment]
Fixed, thanks!
